### ISSUE TITLE
Should not affect RequiredModules

### ISSUE THREAD

**Issue by rondefreitas** [sabinio/AlterPsModuleVersion#9]
with a module version of "1.0.0.1" the following occurs:

**before:**
```
# Version number of this module.
ModuleVersion = '0.0.0.0';

...
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @( `
    @{ ModuleName = 'AzureRM.Network'; ModuleVersion = '5.0.0'; }, `
    @{ ModuleName = 'AzureRM.Profile'; ModuleVersion = '4.0.0'; }, `
    @{ ModuleName = 'AzureRM.HDInsight'; ModuleVersion = '4.0.1'; }, `
    @{ ModuleName = 'AzureRM.DataLakeStore'; ModuleVersion = '5.0.0'; }, `
    @{ ModuleName = 'AzureRM.DataLakeAnalytics'; ModuleVersion = '4.0.0'; }, `
    @{ ModuleName = 'AzureRM.Storage'; ModuleVersion = '4.0.1'; }, `
    @{ ModuleName = 'Azure.Storage'; ModuleVersion = '4.0.0'; } `
    );
```
**after**
```
# Version number of this module.
ModuleVersion = '1.0.0.1';

...
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @( `
    @{ ModuleName = 'AzureRM.Network'; ModuleVersion = '1.0.0.1'; }, `
    @{ ModuleName = 'AzureRM.Profile'; ModuleVersion = '1.0.0.1'; }, `
    @{ ModuleName = 'AzureRM.HDInsight'; ModuleVersion = '1.0.0.1'; }, `
    @{ ModuleName = 'AzureRM.DataLakeStore'; ModuleVersion = '1.0.0.1'; }, `
    @{ ModuleName = 'AzureRM.DataLakeAnalytics'; ModuleVersion = '1.0.0.1'; }, `
    @{ ModuleName = 'AzureRM.Storage'; ModuleVersion = '1.0.0.1'; }, `
    @{ ModuleName = 'Azure.Storage'; ModuleVersion = '1.0.0.1'; } `
    );
```

Adding this script to my build process changed the ModuleVersion on all modules in RequiredModules, which is obviously not desired.

Changing the Module Version should only occur to the first instance of `ModuleVersion = '##.##.##.##'`

**Comment by rondefreitas** [comment]
I don't have time to update your code myself right now but an easy fix might be to change your Regex to `^ModuleVersion(.*)$/m` so this way it should return after the first match where ModuleVersion starts the line.

**Comment by RichieBzzzt** [comment]
Funnily enough I'd made the change before I saw your comment above! Didn't think to change the regex. however I have made a change in version 1.0.2567.0 that will resolve issue. Should be available now in Marketplace. If you can provide feedback here that it works for you I'l close issue.

Thanks again!

**Comment by rondefreitas** [comment]
Thanks Richie. I haven't gotten the chance to test it again, I'll let you know sometime tomorrow :)

**Comment by RichieBzzzt** [comment]
Closing as fixed.
